jwt:
  secret: fadaa4176f9775b7d963e2f562c2adef4858081044ffe11e58e5d3cd6e54dc7d  # sha256 hashcode
  expiration-milliseconds: 1800000    # 30 minutes

spring:
  application:
    name: spring_security_ex
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8
    username: root
    password: 1111

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
# security - step 2
#  security:
#    user:
#      name: test
#      password: 1111
#      roles: USER


