spring:
  application:
    name: spring_security_ex
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8
    username: root
    password: 1111

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
# security - step 2
#  security:
#    user:
#      name: test
#      password: 1111
#      roles: USER
